### ISSUE TITLE
Doesn't work with HP set above max

### ISSUE THREAD

**Issue by amcvfx** [schlosrat/token-health#22] opened 2020-12-17 10:10 UTC
If a token has it's HP Max temporarily increased and their current HP increased Token Health doesn't recognise this and will reduce the Current HP down to match the old max HP regardless of what value is entered in the pop up box. 
This image shows how it is set before token health is applied (this comes from a spell like Aid). Token Health will drop the HP to 80 if any value less than 10 is entered.

![image](https://user-images.githubusercontent.com/35099081/102473827-34ad3b80-4058-11eb-96e3-eb6b0aa28699.png)

**Comment by DarKDinDoN** [comment] 2021-03-05 13:16
Same here.

**Comment by schlosrat** [comment] 2021-05-01 17:02
This may be something that can be fixed by pointing Token Health at the actor attribute that has the actual max you'd like it to use. For example in dnd5e, pf1, and pf2e the default setting is "attributes.hp.max", but in age-system it's "health.value", and in all others the default is "health.max".

Please try this:
Create a script macro with one line that says "console.log(actor)"
Select a token which has an elevated max hp and execute the macro with that token selected
Open the console and examine the actor object to see if you can identify the correct attribute that holds the actual value needed in this case

If you're able to find that information in the actor object structure you can configure this correctly in the Token Health module settings for Max Hit Points Source.

If you're having trouble with this process please reply to let me know which game system you're using and I'll see if I can replicate this at my end.

**Comment by DarKDinDoN** [comment] 2021-05-01 18:45
@schlosrat I use 5e latest version.
By using "attributes.hp.max", I can't get the same behavior as illustrated in the first post. (current hp above, max HP).

**Comment by schlosrat** [comment] 2021-05-01 21:54
Thanks! I'll see if I can replicate this at my end. If I can, then I should be able to fix it.

**Comment by DarKDinDoN** [comment] 2021-05-01 22:02
@schlosrat That is what a character data with 10 Max temp HP looks like:
![image](https://user-images.githubusercontent.com/1687854/116796003-612e9500-aad9-11eb-9516-9ad4dcadf0e8.png)
"max" value represents the max HP without max temp HP.

So for the module to work, it should add "tempmax" to "max".

**Comment by schlosrat** [comment] 2021-05-05 00:24
This appears to be working correctly. Here's what I've done to test it. FYI - I did this with the "Clash at the Kobold Cauldron"  dnd5e world, testing in "The Costal Road" scene.

1. Create script to add 10 temp hp to the selected token
```js
let temp_hp = actor.data.data.attributes.hp.temp;
temp_hp = temp_hp + 10;
actor.update({"data.attributes.hp.temp": temp_hp})
```
2. Use Token Health to apply 5 points of damage to Kollias token. Checked the actor data to confirm max = 58, min = 0, temp = 0, and value = 53. So hp.value is the current value of real hp.
3. Use script to add 10 temp hp. Checked the actor data to confirm max = 58, min =0, temp =10, value = 53. This is correct since adding temp hp doesn't change the quantity of real hp an actor has, but it does add to the overall total.
4. Use Token Health to apply 6 points of damage to Kollias token. Checked the actor data to confirm max = 58, min = 0, temp = 4, and vlaue = 53. So all 6 points of damage were taken from the hp.temp source as they should be.
5. Use Token Health to apply 7 points of damage to Kollias token. Checked the actor data to confirm max = 58, min = 0, temp = 0, value = 50. This correctly applied 4 points of damage to the hp.temp taking that to 0 and the remaining 3 points of damage to hp.value as they should be applied.
6. Use Token Health to apply 99 point of healing to Kollias token. Checked the actor data to confirm max = 58, min = 0, temp = 0, and value = 58. Extra healing is waisted, and one temp hp are gone they don't come back with healing.

This is all done with the dnd53 default settings in Token Health where current hit points are attributes.hp.value, max are attributes.hp.max, and temporary hp are attributes.hp.temp. Please make sure those are the settings you're using in dnd5e. If so, then this should be the expected behavior. If you try a test like this with these same settings you should see the same thing. If you don't see results as I've described above please let me know.

**Closed by schlosrat** 2021-05-05 00:24 UTC

**Comment by DarKDinDoN** [comment] 2021-05-05 08:48
@schlosrat That's because you are testing with "temp hit points" and not "**max** temp hit points".
- Temp hit points act as some kind of shield and are working correctly 👍 
- **Max** temp hit points are representing an added value to the **max** hit points of the character (but temporary). Meaning if a character has a **max** health of 80 hp and gets 10 **max** temp hit points. Until the effect is removed, the real **max** health of the character is actually 90 and not 80. Note that it also works with negative values. If the character has a **max** health of 80 hp and gets -10 **max** temp hit points, the real **max** health of the character is actually 70 and not 80 (until the effect is removed).

Here is a demo video about the issue.
Quick note: the script shouldn't change the **max** temp hit points value, but should change the current hit points accordingly.
Also here is a spell example of such and effect: https://www.dndbeyond.com/spells/aid. By using this spell on a character, this character gets 5 max temp hit points + 5 hit points (the last part is not relevant to the issue).

https://user-images.githubusercontent.com/1687854/117115901-02457600-ad8e-11eb-91d6-13c9b8fbd6dd.mp4

**Comment by DarKDinDoN** [comment] 2021-05-16 18:27
@schlosrat Hello, is this handled with 0.3.0? Not sure if I missed smt.
Anyway thank you for the latest release!
